#!/usr/bin/env python

from yaphe.helpers import *
page = html_transitional_page()
html = elem('html')
head = elem('head')
head += elem('title', 'A Test Page')
head += screen_css('/static/home.css')
html += head

body = elem('body')
content = elem('#content')
content += img('/static/logo.png')
content += elem('h2#tagline', 'This has a ' + elem('span#highlight', 'span') +\
                    ' element.')
body += content
html += body
page += html
print page.render()
